steps:

# Install dependencies
- name: node:16.7.0
  entrypoint: yarn
  args: ['install']

# Build with webpack
- name: node:16.7.0
  entrypoint: yarn
  args: ['run', 'build']

# Copy build files to cloud storage location
- name: gcr.io/cloud-builders/gsutil
  args: [ "-m", "rsync", "-r", "-c", "-d", "./build", "gs://bitcoin.craighammell.com" ]
